In [12]:
class MyLR:
    def __init__(self):
        self.m=None
        self.b=None
    def fit(self,x_train,y_train):
        num=0
        den=0

        for i in range(x_train.shape[0]):
            num=num + ((x_train[i]-x_train.mean())*(y_train[i]-y_train.mean()))
            den=den + ((x_train[i]-x_train.mean())*(x_train[i]-x_train.mean()))

            self.m=num/den
            self.b=y_train.mean() - (self.m*x_train.mean())
            print(self.m)
            print(self.b)
    def predict(self,x_test):
        return self.m*x_test+self.b

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('placement (2).csv')

In [4]:
df.head()

,cgpa,package
0,6.89,3.26
1,5.12,1.98
2,7.82,3.25
3,7.42,3.67
4,6.94,3.57


In [5]:
x=df.iloc[:,0:1].values
y=df.iloc[:,1].values

In [6]:
x

array([[6.89],
       [5.12],
       [7.82],
       [7.42],
       [6.94],
       [7.89],
       [6.73],
       [6.75],
       [6.09],
       [8.31],
       [5.32],
       [6.61],
       [8.94],
       [6.93],
       [7.73],
       [7.25],
       [6.84],
       [5.38],
       [6.94],
       [7.48],
       [7.28],
       [6.85],
       [6.14],
       [6.19],
       [6.53],
       [7.28],
       [8.31],
       [5.42],
       [5.94],
       [7.15],
       [7.36],
       [8.1 ],
       [6.96],
       [6.35],
       [7.34],
       [6.87],
       [5.99],
       [5.9 ],
       [8.62],
       [7.43],
       [9.38],
       [6.89],
       [5.95],
       [7.66],
       [5.09],
       [7.87],
       [6.07],
       [5.84],
       [8.63],
       [8.87],
       [9.58],
       [9.26],
       [8.37],
       [6.47],
       [6.86],
       [8.2 ],
       [5.84],
       [6.6 ],
       [6.92],
       [7.56],
       [5.61],
       [5.48],
       [6.34],
       [9.16],
       [7.36],
       [7.6 ],
       [5.

In [7]:
y

array([3.26, 1.98, 3.25, 3.67, 3.57, 2.99, 2.6 , 2.48, 2.31, 3.51, 1.86,
       2.6 , 3.65, 2.89, 3.42, 3.23, 2.35, 2.09, 2.98, 2.83, 3.16, 2.93,
       2.3 , 2.48, 2.71, 3.65, 3.42, 2.16, 2.24, 3.49, 3.26, 3.89, 3.08,
       2.73, 3.42, 2.87, 2.84, 2.43, 4.36, 3.33, 4.02, 2.7 , 2.54, 2.76,
       1.86, 3.58, 2.26, 3.26, 4.09, 4.62, 4.43, 3.79, 4.11, 2.61, 3.09,
       3.39, 2.74, 1.94, 3.09, 3.31, 2.19, 1.61, 2.09, 4.25, 2.92, 3.81,
       1.63, 2.89, 2.99, 2.94, 2.35, 3.34, 3.62, 4.03, 3.44, 3.28, 3.15,
       4.6 , 2.21, 3.  , 3.44, 2.2 , 2.17, 3.49, 1.53, 1.48, 2.77, 3.55,
       1.48, 2.72, 2.66, 2.14, 4.  , 3.08, 2.42, 2.79, 2.61, 2.84, 3.83,
       3.24, 4.14, 3.52, 1.37, 3.  , 3.74, 2.82, 2.19, 2.59, 3.54, 4.06,
       3.76, 2.25, 4.1 , 2.37, 1.87, 4.21, 3.33, 2.99, 2.88, 2.65, 1.73,
       3.02, 2.01, 2.3 , 2.31, 3.16, 2.6 , 3.11, 3.34, 3.12, 2.49, 2.01,
       2.48, 2.58, 2.83, 2.6 , 2.1 , 3.13, 3.89, 2.4 , 3.15, 3.18, 3.04,
       1.54, 2.42, 2.18, 2.46, 2.21, 3.4 , 3.67, 2.

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [9]:
x_train.shape

(160, 1)

In [16]:
lr=MyLR()

In [17]:
lr.fit(x_train,y_train)

[0.84006664]
[-2.8680758]
[0.46924607]
[-0.27606319]
[0.47357848]
[-0.3063465]
[0.43681145]
[-0.04934724]
[0.49030328]
[-0.42325179]
[0.4839694]
[-0.37897834]
[0.48640321]
[-0.39599052]
[0.49703213]
[-0.47028605]
[0.47199392]
[-0.29527053]
[0.43974818]
[-0.06987478]
[0.47590917]
[-0.32263787]
[0.51633972]
[-0.6052449]
[0.52119086]
[-0.63915405]
[0.5291616]
[-0.69486903]
[0.53052812]
[-0.70442091]
[0.52992237]
[-0.70018678]
[0.56393834]
[-0.93795626]
[0.57167524]
[-0.99203668]
[0.57294557]
[-1.00091624]
[0.57402428]
[-1.00845632]
[0.58145189]
[-1.06037485]
[0.5765852]
[-1.026357]
[0.57265117]
[-0.99885839]
[0.56740905]
[-0.96221631]
[0.5710666]
[-0.98778236]
[0.57227836]
[-0.99625248]
[0.562582]
[-0.92847553]
[0.57069231]
[-0.98516609]
[0.57278178]
[-0.99977136]
[0.5854696]
[-1.08845843]
[0.58185579]
[-1.06319811]
[0.58331111]
[-1.07337067]
[0.58346342]
[-1.07443535]
[0.58297067]
[-1.07099108]
[0.5803811]
[-1.05289015]
[0.57549084]
[-1.01870748]
[0.57602267]
[-1.02242493]
[0.57408152]
[

In [18]:
x_test[0]

array([8.58])

In [19]:
print(lr.predict(x_test[0]))

None
